name: CI

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zig:
    name: Zig ${{ matrix.zig-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        zig-version:
          - 0.15.1
          - 0.15.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Zig Version
        run: zig version

      - name: Run Tests
        run: zig build test

      - name: Run Examples
        run: zig build examples
